-- Insert jewellery templates for girls page
INSERT INTO templates (id, title, description, image_url, ai_prompt, category, tags, is_active, display_order) VALUES
(62, 'Golden Elegance Necklace', 'Adorn yourself with stunning golden jewelry that radiates sophistication', '/cdn/jewellery-golden.jpg', 'Create a photorealistic portrait of the person wearing an elegant golden necklace set with matching earrings. The jewelry should feature intricate designs with delicate chains, pendant details, and polished gold finish. Maintain the person\'s exact facial features, skin tone, and natural beauty. The jewelry should complement their neckline beautifully. Natural lighting, soft shadows, premium quality photography, 8K HD.', 'jewellery', 'jewellery,necklace,golden,elegant,accessories', TRUE, 62),

(63, 'Diamond Princess Set', 'Experience royal elegance with sparkling diamond jewelry collection', '/cdn/jewellery-diamond.jpg', 'Create a photorealistic portrait of the person wearing a luxurious diamond jewelry set including necklace, earrings, and accessories. The diamonds should sparkle realistically with brilliant cuts catching light beautifully. Maintain exact facial features and skin tone. The jewelry should look premium and elegant. Studio lighting with soft glow, high-end fashion photography style, 8K HD quality.', 'jewellery', 'jewellery,diamond,luxury,princess,sparkle', TRUE, 63),

(64, 'Pearl Classic Beauty', 'Timeless pearl jewelry that adds grace and sophistication', '/cdn/jewellery-pearl.jpg', 'Create a photorealistic portrait of the person wearing classic pearl jewelry including pearl necklace and matching pearl earrings. The pearls should have natural luster and soft cream-white color. Maintain the person\'s exact facial features and natural skin tone. The jewelry should look elegant and timeless. Soft natural lighting, refined elegance, 8K HD premium quality.', 'jewellery', 'jewellery,pearl,classic,elegant,timeless', TRUE, 64),

(65, 'Ruby Royal Collection', 'Bold ruby jewelry pieces that make a stunning statement', '/cdn/jewellery-ruby.jpg', 'Create a photorealistic portrait of the person wearing exquisite ruby jewelry set with necklace and earrings. The rubies should have deep red color with metallic gold or silver settings. Maintain exact facial features and skin tone. The jewelry should look bold yet elegant. Dramatic lighting highlighting the jewelry, luxury fashion photography, 8K HD quality.', 'jewellery', 'jewellery,ruby,red,bold,statement', TRUE, 65),

(66, 'Emerald Garden Set', 'Enchanting emerald jewelry inspired by nature\'s beauty', '/cdn/jewellery-emerald.jpg', 'Create a photorealistic portrait of the person wearing beautiful emerald jewelry set featuring green gemstones in elegant gold settings. Include necklace and earrings with emerald stones. Maintain the person\'s exact facial features and natural skin tone. The jewelry should look sophisticated and nature-inspired. Natural daylight, elegant composition, 8K HD premium quality.', 'jewellery', 'jewellery,emerald,green,nature,elegant', TRUE, 66),

(67, 'Silver Moonlight Charm', 'Delicate silver jewelry with contemporary minimalist design', '/cdn/jewellery-silver.jpg', 'Create a photorealistic portrait of the person wearing modern silver jewelry including a delicate silver necklace with pendant and matching earrings. The silver should have polished metallic finish with contemporary minimal design. Maintain exact facial features and skin tone. The jewelry should look trendy and elegant. Soft natural lighting, modern fashion photography, 8K HD quality.', 'jewellery', 'jewellery,silver,modern,minimalist,trendy', TRUE, 67);
